#!/usr/bin/env bash
# Installs a `remtui` launcher into the same directory as remctl
# (or into --dir DIR). The launcher runs the project's uv-managed venv,
# so `git pull && ./install.sh` is also the update path.
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

usage() {
    cat <<EOF
Usage: ./install.sh [--dir DIR] [--uninstall]

  --dir DIR     install the launcher into DIR instead of auto-detecting
  --uninstall   remove a previously installed launcher

Without --dir, the launcher is installed next to remctl if it can be
found (PATH, then ~/bin, ~/.local/bin, /usr/local/bin, /opt/homebrew/bin),
falling back to ~/.local/bin.
EOF
}

die() { echo "install.sh: $*" >&2; exit 1; }

TARGET_DIR=""
UNINSTALL=0
while [ $# -gt 0 ]; do
    case "$1" in
        --dir) [ $# -ge 2 ] || die "--dir needs an argument"; TARGET_DIR="$2"; shift 2 ;;
        --uninstall) UNINSTALL=1; shift ;;
        -h|--help) usage; exit 0 ;;
        *) usage >&2; die "unknown option: $1" ;;
    esac
done

detect_target_dir() {
    local found
    if found="$(command -v remctl 2>/dev/null)"; then
        dirname "$found"
        return
    fi
    local candidate
    for candidate in "$HOME/bin" "$HOME/.local/bin" /usr/local/bin /opt/homebrew/bin; do
        if [ -x "$candidate/remctl" ]; then
            echo "$candidate"
            return
        fi
    done
    echo "$HOME/.local/bin"
}

if [ -z "$TARGET_DIR" ]; then
    TARGET_DIR="$(detect_target_dir)"
    if [ -x "$TARGET_DIR/remctl" ]; then
        echo "Found remctl in $TARGET_DIR"
    else
        echo "remctl not found; defaulting to $TARGET_DIR"
    fi
fi

LAUNCHER="$TARGET_DIR/remtui"

if [ "$UNINSTALL" -eq 1 ]; then
    if [ -e "$LAUNCHER" ]; then
        rm "$LAUNCHER"
        echo "Removed $LAUNCHER"
    else
        echo "Nothing to remove at $LAUNCHER"
    fi
    exit 0
fi

command -v uv >/dev/null 2>&1 || die "uv is required — install it from https://docs.astral.sh/uv/"

echo "Syncing project environment in $PROJECT_DIR …"
(cd "$PROJECT_DIR" && uv sync --quiet)

VENV_REMTUI="$PROJECT_DIR/.venv/bin/remtui"
[ -x "$VENV_REMTUI" ] || die "expected $VENV_REMTUI after uv sync — is pyproject.toml intact?"

mkdir -p "$TARGET_DIR"
cat > "$LAUNCHER" <<EOF
#!/bin/sh
# remtui launcher — generated by install.sh, runs out of $PROJECT_DIR
if [ ! -x "$VENV_REMTUI" ]; then
    echo "remtui: missing $VENV_REMTUI — re-run $PROJECT_DIR/install.sh" >&2
    exit 1
fi
exec "$VENV_REMTUI" "\$@"
EOF
chmod +x "$LAUNCHER"

echo "Installed $LAUNCHER"
case ":$PATH:" in
    *":$TARGET_DIR:"*) ;;
    *) echo "note: $TARGET_DIR is not on this shell's PATH" ;;
esac
