#!/usr/bin/env bash
# Installs a `remtui` launcher into ~/bin (or --dir DIR). The launcher runs the
# project's uv-managed venv, so `git pull && ./install.sh` is also the update
# path.
#
# The same script, with the same defaults, ships in librarian, remtui, and
# taskpapertui: one install command to learn, one place the binaries land.
set -euo pipefail

APP="remtui"
PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEFAULT_DIR="$HOME/bin"

usage() {
    cat <<EOF
Usage: ./install.sh [--dir DIR] [--uninstall]

  --dir DIR     install the launcher into DIR instead of $DEFAULT_DIR
  --uninstall   remove a previously installed launcher

Config lives in \${XDG_CONFIG_HOME:-\$HOME/.config}/$APP/config.toml and is
left alone by both install and uninstall.
EOF
}

die() { echo "install.sh: $*" >&2; exit 1; }

TARGET_DIR="$DEFAULT_DIR"
UNINSTALL=0
while [ $# -gt 0 ]; do
    case "$1" in
        --dir) [ $# -ge 2 ] || die "--dir needs an argument"; TARGET_DIR="$2"; shift 2 ;;
        --uninstall) UNINSTALL=1; shift ;;
        -h|--help) usage; exit 0 ;;
        *) usage >&2; die "unknown option: $1" ;;
    esac
done

LAUNCHER="$TARGET_DIR/$APP"

if [ "$UNINSTALL" -eq 1 ]; then
    if [ -e "$LAUNCHER" ]; then
        rm "$LAUNCHER"
        echo "Removed $LAUNCHER"
    else
        echo "Nothing to remove at $LAUNCHER"
    fi
    exit 0
fi

command -v uv >/dev/null 2>&1 || die "uv is required — install it from https://docs.astral.sh/uv/"

echo "Syncing project environment in $PROJECT_DIR …"
(cd "$PROJECT_DIR" && uv sync --quiet)

VENV_BIN="$PROJECT_DIR/.venv/bin/$APP"
[ -x "$VENV_BIN" ] || die "expected $VENV_BIN after uv sync — is pyproject.toml intact?"

mkdir -p "$TARGET_DIR"
cat > "$LAUNCHER" <<EOF
#!/bin/sh
# $APP launcher — generated by install.sh, runs out of $PROJECT_DIR
if [ ! -x "$VENV_BIN" ]; then
    echo "$APP: missing $VENV_BIN — re-run $PROJECT_DIR/install.sh" >&2
    exit 1
fi
exec "$VENV_BIN" "\$@"
EOF
chmod +x "$LAUNCHER"

echo "Installed $LAUNCHER"
case ":$PATH:" in
    *":$TARGET_DIR:"*) ;;
    *) echo "note: $TARGET_DIR is not on this shell's PATH — add it to use \`$APP\`" ;;
esac
